language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements_raw_files.txt
  - pip install nose
  - pip install coverage
  - pip install coveralls

# command to run tests
script:
  - nosetests
  - coverage run --source=tests setup.py test

after_success:
  - coveralls