language: python
python:
  - "3.6"

# command to install dependencies
install:
  - wget http://build.berkeleybop.org/userContent/owltools/owltools
  - chmod +x owltools
  - export PATH=$PATH:$PWD
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
  - pip install coveralls

# command to run tests
script:
  - nosetests
  - coverage run --source=tests setup.py test

after_success:
  - coveralls